apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: job-manager
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: api-sa
    namespace: dev
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
