apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "123456"
  CONNECTION_STRING: "Host=postgres.dev.svc.cluster.local;Database=leadlists;Username=postgres;Password=123456"
  
