apiVersion: v1
clusters:
- cluster:
    server: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
  name: api-sandbox-m2-ll9k-p1-openshiftapps-com:6443
- cluster:
    server: https://0.0.0.0:39423
  name: k3d-leadlists
contexts:
- context:
    cluster: k3d-leadlists
    user: admin@k3d-leadlists
  name: k3d-leadlists
current-context: k3d-leadlists
kind: Config
users:
- name: admin@k3d-leadlists
  user:
- name: finall00/api-sandbox-m2-ll9k-p1-openshiftapps-com:6443
  user:
    token: 
