name: Build and Push API and Worker to Docker Hub

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copie job-template to API context
        run: cp ./K8s/worker/job-template.yaml ./API/job-template.yaml

      - name: Extract metadata (tags, labels) for API
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: finall00/leadlist-api

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./API/
          file: ./API/Dockerfile
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels}}

      - name: Extract metadata (tags, labels) for worker Docker
        id: meta-worker
        uses: docker/metadata-action@v5
        with:
          images: finall00/leadlist-worker

      - name: Build and push Worker image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: ${{ steps.meta-worker.outputs.tags}}
          labels: ${{ steps.meta-worker.outputs.labels }}
